(function(){
  "use strict";
  function render(state,h){const section=state.activeSections.ADMIN;document.getElementById("view-admin").innerHTML='<header class="portal-context"><p class="eyebrow">Adminportal · Demo-Zugang</p><h1>Plattformverwaltung</h1><p class="muted">Freigaben, Vorgänge und Plattformqualität zentral steuern.</p></header>'+window.AutoAnonymNavigation.render("ADMIN",section,[])+`<div class="portal-content">${content(section,state,h)}</div>`;}
  function content(section,state,h){if(section==="dashboard")return dashboard(state);if(section==="werkstaetten")return providers(state,h,"werkstatt","Werkstätten");if(section==="gutachter")return providers(state,h,"gutachter","Gutachter");if(section==="kunden")return customers();if(section==="auftraege")return orders(state,h);if(section==="support")return support(state,h);if(section==="zahlungen")return placeholder("Zahlungen","Zahlungsvorgänge und Provisionen werden erst mit einer sicheren Zahlungsanbindung aktiviert.");if(section==="bewertungen")return placeholder("Bewertungen","Bewertungen werden später auf abgeschlossene und verifizierte Aufträge begrenzt.");if(section==="benachrichtigungen")return window.AutoAnonymBenachrichtigungen.inline(state,h,"ADMIN");return settings();}
  function dashboard(state){const pending=Object.values(state.providers).filter((item)=>item.status==="IN_PRUEFUNG").length;return `<section class="grid grid-3"><article class="card metric-card"><p class="eyebrow">Offene Prüfungen</p><div class="metric">${pending}</div><p class="small muted">Werkstätten und Gutachter</p></article><article class="card metric-card"><p class="eyebrow">Kunden</p><div class="metric">24</div><p class="small muted">18 verifiziert</p></article><article class="card metric-card"><p class="eyebrow">Vorgänge</p><div class="metric">${state.requests.length}</div><p class="small muted">Anfragen und Aufträge</p></article><article class="card metric-card"><p class="eyebrow">Support eskaliert</p><div class="metric">${state.supportCases.filter((item)=>item.status==="ESKALIERT").length}</div></article><article class="card metric-card"><p class="eyebrow">Offene Angebote</p><div class="metric">${state.offers.filter((item)=>!item.accepted).length}</div></article><article class="card metric-card"><p class="eyebrow">Ungelesene Hinweise</p><div class="metric">${state.notifications.filter((item)=>item.targetRole==="ADMIN"&&!item.read).length}</div></article></section>`;}
  function providers(state,h,key,title){const p=state.providers[key];return `<section><div class="section-heading"><div><p class="eyebrow">Partnerprüfung</p><h2>${title}</h2></div></div><article class="card"><div class="split"><div>${window.AutoAnonymStatus.badge(p.status)}<h3>${h(p.name)}</h3><p class="muted">${h(p.id)} · Bedingungen ${p.termsAccepted?"akzeptiert":"offen"}</p></div></div><div class="action-row"><button class="button button-success" type="button" data-provider-status="${key}:FREIGEGEBEN" ${p.status==="FREIGEGEBEN"?"disabled":""}>Freigeben</button><button class="button button-warning" type="button" data-provider-status="${key}:ABGELEHNT" ${p.status==="ABGELEHNT"?"disabled":""}>Ablehnen</button><button class="button button-danger" type="button" data-provider-status="${key}:GESPERRT" ${p.status==="GESPERRT"?"disabled":""}>Sperren</button><button class="button button-secondary" type="button" data-provider-status="${key}:IN_PRUEFUNG" ${p.status==="IN_PRUEFUNG"?"disabled":""}>Erneut prüfen</button></div>${p.statusReason?`<p class="note small"><strong>Letzte Begründung:</strong> ${h(p.statusReason)}</p>`:""}</article></section>`;}
  function customers(){return '<section><p class="eyebrow">Kundenverwaltung</p><h2>Kunden</h2><div class="stack"><article class="list-card"><strong>Kunde #A-204</strong><p class="small muted">2 Fahrzeuge · Konto verifiziert · 2 Vorgänge</p></article><article class="list-card"><strong>Kunde #A-198</strong><p class="small muted">1 Fahrzeug · Konto verifiziert · kein offener Vorgang</p></article></div></section>';}
  function orders(state,h){return `<section><p class="eyebrow">Plattformweit</p><h2>Aufträge und Anfragen</h2><div class="stack">${state.requests.map((item)=>`<article class="list-card"><div class="split"><div>${window.AutoAnonymStatus.badge(item.status)}<h3>${h(item.id)} · ${h(item.typeLabel)}</h3></div><strong>${h(item.vehicleName)}</strong></div><p>${h(item.description)}</p></article>`).join("")}</div></section>`;}
  function support(state,h){return `<section><p class="eyebrow">Eskalationsübersicht</p><h2>Supportfälle</h2><div class="stack">${state.supportCases.map((item)=>`<article class="list-card"><div class="split"><div>${window.AutoAnonymStatus.badge(item.status)}<h3>${h(item.title)}</h3></div><span>${h(item.id)}</span></div></article>`).join("")}</div></section>`;}
  function placeholder(title,text){return `<section class="placeholder-panel"><p class="eyebrow">Vorbereitet</p><h2>${title}</h2><p class="muted">${text}</p><span class="badge badge-info">Frontend-Platzhalter</span></section>`;}
  function settings(){return '<section class="grid grid-2"><article class="card"><p class="eyebrow">Plattform</p><h2>Einstellungen</h2><div class="field"><label for="commission">Demo-Provision in Prozent</label><input id="commission" type="number" value="12" min="0" max="100"></div></article><article class="card"><p class="eyebrow">Sicherheit</p><h2>Administrationszugang</h2><p class="muted">Im Frontend-Prototyp nur simuliert. Eine echte Rechteprüfung folgt mit dem Backend.</p></article></section>';}
  window.AutoAnonymAdmin={render};
}());
