(function(){
  "use strict";
  const state={
    currentRole:"KUNDE",
    activeSections:{KUNDE:"start",WERKSTATT:"dashboard",GUTACHTER:"dashboard",KUNDENSUPPORT:"dashboard",ADMIN:"dashboard"},
    activeConversations:{},requestFocus:null,
    roleLabels:{KUNDE:"Kunde",WERKSTATT:"Werkstatt",GUTACHTER:"Gutachter",KUNDENSUPPORT:"Kundensupport",ADMIN:"Admin"},
    nextIds:{request:103,offer:503,vehicle:3,message:706,notification:806,support:303,conversation:5},
    vehicles:[{id:"VEH-1",name:"Peugeot 407 Coupé",plate:"BN-FK 2026",vin:"VF36D…9823"},{id:"VEH-2",name:"Volkswagen ID.3",plate:"BN-AA 481",vin:"WVWZZZ…1842"}],
    requests:[{id:"REQ-101",type:"REPARATUR",typeLabel:"Reparatur",vehicleId:"VEH-1",vehicleName:"Peugeot 407 Coupé",description:"Keilriemen wechseln und Riemenspanner überprüfen.",date:"2026-08-18",status:"OFFEN",statusLabel:"Offen"},{id:"REQ-102",type:"GUTACHTEN",typeLabel:"Gutachten",vehicleId:"VEH-2",vehicleName:"Volkswagen ID.3",description:"Bewertung eines Parkschadens an der Beifahrertür.",date:"2026-08-21",status:"OFFEN",statusLabel:"Offen",reportUploaded:false}],
    offers:[{id:"OFF-501",requestId:"REQ-101",providerRole:"WERKSTATT",provider:"Werkstatt #421 · Bonn",price:"280,00",date:"18.08.2026",duration:"Etwa 3–4 Stunden",cancellation:"Kostenfrei bis 24 Stunden vor Termin",accepted:false},{id:"OFF-502",requestId:"REQ-102",providerRole:"GUTACHTER",provider:"Gutachter #207 · Bonn",price:"195,00",date:"21.08.2026",duration:"Besichtigung etwa 60 Minuten",cancellation:"Kostenfrei bis 12 Stunden vor Termin",accepted:false}],
    providers:{werkstatt:{id:"WS-309",name:"Kfz-Meisterbetrieb Bonn",status:"IN_PRUEFUNG",termsAccepted:true,statusReason:""},gutachter:{id:"GA-118",name:"Kfz-Sachverständigenbüro Rhein",status:"IN_PRUEFUNG",termsAccepted:true,statusReason:""}},
    notifications:[{id:"NOT-801",type:"NEUES_ANGEBOT",text:"Für REQ-101 ist ein neues Werkstattangebot eingegangen.",targetRole:"KUNDE",createdAt:"2026-08-08T10:10:00",read:false},{id:"NOT-802",type:"NEUE_NACHRICHT",text:"Werkstatt #421 hat eine Rückfrage gesendet.",targetRole:"KUNDE",createdAt:"2026-08-08T10:15:00",read:false},{id:"NOT-803",type:"FREIGABESTATUS",text:"Ihre Werkstattregistrierung wird geprüft.",targetRole:"WERKSTATT",createdAt:"2026-08-08T09:00:00",read:false},{id:"NOT-804",type:"FREIGABESTATUS",text:"Ihre Gutachterregistrierung wird geprüft.",targetRole:"GUTACHTER",createdAt:"2026-08-08T09:05:00",read:false},{id:"NOT-805",type:"SUPPORTANTWORT",text:"Zu Ihrem Supportfall liegt eine neue Antwort vor.",targetRole:"KUNDE",createdAt:"2026-08-07T15:30:00",read:true}],
    supportCases:[{id:"SUP-301",title:"Terminabstimmung zu REQ-101",status:"IN_BEARBEITUNG",statusLabel:"In Bearbeitung",participants:["Kunde #A-204","Werkstatt #421"],notes:["Rückmeldung der Werkstatt bis morgen abwarten."]},{id:"SUP-302",title:"Dokument für Gutachten fehlt",status:"OFFEN",statusLabel:"Offen",participants:["Kunde #A-204","Gutachter #207"],notes:[]}],
    conversations:[
      {id:"CONV-1",type:"REPARATURANFRAGE",typeLabel:"Reparaturanfrage",contextId:"REQ-101",title:"Keilriemen und Riemenspanner",roles:["KUNDE","WERKSTATT"],participants:[{role:"KUNDE",label:"Alex Beispiel",anonymousLabel:"Kunde #A-204"},{role:"WERKSTATT",label:"Kfz-Meisterbetrieb Bonn",anonymousLabel:"Werkstatt #421"}],messages:[{id:"MSG-701",senderRole:"WERKSTATT",sender:"Werkstatt #421",text:"Sind Geräusche nur beim Kaltstart zu hören?",createdAt:"2026-08-08T10:15:00",readBy:["WERKSTATT"]},{id:"MSG-702",senderRole:"KUNDE",sender:"Kunde #A-204",text:"Ja, nach wenigen Minuten wird es deutlich leiser.",createdAt:"2026-08-08T10:21:00",readBy:["KUNDE","WERKSTATT"]}]},
      {id:"CONV-2",type:"GUTACHTERANFRAGE",typeLabel:"Gutachteranfrage",contextId:"REQ-102",title:"Parkschaden Beifahrertür",roles:["KUNDE","GUTACHTER"],participants:[{role:"KUNDE",label:"Alex Beispiel",anonymousLabel:"Kunde #A-204"},{role:"GUTACHTER",label:"Sachverständigenbüro",anonymousLabel:"Gutachter #207"}],messages:[{id:"MSG-703",senderRole:"GUTACHTER",sender:"Gutachter #207",text:"Bitte halten Sie den Fahrzeugschein zum Termin bereit.",createdAt:"2026-08-08T11:05:00",readBy:["GUTACHTER"]}]},
      {id:"CONV-3",type:"AUFTRAG",typeLabel:"Auftrag",contextId:"AUF-081",title:"Bremsenservice – abgeschlossen",roles:["KUNDE","WERKSTATT"],participants:[{role:"KUNDE",label:"Alex Beispiel",anonymousLabel:"Kunde #A-204"},{role:"WERKSTATT",label:"Werkstatt #388",anonymousLabel:"Werkstatt #388"}],messages:[{id:"MSG-704",senderRole:"WERKSTATT",sender:"Werkstatt #388",text:"Ihr Fahrzeug steht zur Abholung bereit.",createdAt:"2026-08-06T15:00:00",readBy:["WERKSTATT","KUNDE"]}]},
      {id:"CONV-4",type:"SUPPORTFALL",typeLabel:"Supportfall",contextId:"SUP-301",title:"Terminabstimmung zu REQ-101",roles:["KUNDE","KUNDENSUPPORT","WERKSTATT"],participants:[{role:"KUNDE",label:"Alex Beispiel"},{role:"KUNDENSUPPORT",label:"AutoAnonym Kundensupport"},{role:"WERKSTATT",label:"Werkstatt #421",anonymousLabel:"Werkstatt #421"}],messages:[{id:"MSG-705",senderRole:"KUNDENSUPPORT",sender:"Kundensupport",text:"Wir haben die Werkstatt um eine Rückmeldung gebeten.",createdAt:"2026-08-07T15:30:00",readBy:["KUNDENSUPPORT","KUNDE"]}]}
    ]
  };
  const modules={KUNDE:window.AutoAnonymKunde,WERKSTATT:window.AutoAnonymWerkstatt,GUTACHTER:window.AutoAnonymGutachter,KUNDENSUPPORT:window.AutoAnonymSupport,ADMIN:window.AutoAnonymAdmin};
  let lastFocusedElement=null,pendingConfirmation=null;
  function escapeHtml(value){return String(value??"").replace(/[&<>'"]/g,(character)=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[character]));}
  function render(){modules[state.currentRole].render(state,escapeHtml);document.querySelectorAll(".role-view").forEach((view)=>{view.hidden=view.id!==`view-${state.currentRole.toLowerCase()}`;});document.querySelectorAll("[data-role-target]").forEach((button)=>button.classList.toggle("active",button.dataset.roleTarget===state.currentRole));document.getElementById("portal-role-label").textContent=window.AutoAnonymNavigation.portalName(state.currentRole);window.AutoAnonymBenachrichtigungen.render(state,escapeHtml);focusRequestedForm();}
  function switchRole(role){if(!modules[role])return;state.currentRole=role;closeDemoPanel();render();document.getElementById("hauptinhalt").focus({preventScroll:true});window.scrollTo({top:0,behavior:"smooth"});}
  function switchSection(section,focus){state.activeSections[state.currentRole]=section;if(focus)state.requestFocus=focus;render();window.scrollTo({top:0,behavior:"smooth"});}
  function focusRequestedForm(){if(!state.requestFocus)return;const id=state.requestFocus==="repair"?"repair-description":"expert-description";state.requestFocus=null;window.setTimeout(()=>document.getElementById(id)?.focus(),0);}
  function notify(type,text,targetRole){window.AutoAnonymBenachrichtigungen.create(state,type,text,targetRole);}
  function showToast(text){const toast=document.createElement("div");toast.className="toast";toast.textContent=text;document.getElementById("toast-region").appendChild(toast);window.setTimeout(()=>toast.remove(),3500);}
  function openModal(title,content){lastFocusedElement=document.activeElement;document.getElementById("modal-title").textContent=title;document.getElementById("modal-content").innerHTML=content;document.getElementById("modal-backdrop").hidden=false;document.body.style.overflow="hidden";document.getElementById("modal-close").focus();}
  function closeModal(){document.getElementById("modal-backdrop").hidden=true;document.body.style.overflow="";pendingConfirmation=null;if(lastFocusedElement instanceof HTMLElement)lastFocusedElement.focus();}
  function confirmAction(options,callback){pendingConfirmation=callback;openModal(options.title,window.AutoAnonymDialoge.confirmationContent(options));}
  function openNotifications(){window.AutoAnonymBenachrichtigungen.render(state,escapeHtml);document.getElementById("drawer-backdrop").hidden=false;const drawer=document.getElementById("notifications-drawer");drawer.classList.add("open");drawer.setAttribute("aria-hidden","false");document.body.style.overflow="hidden";document.getElementById("notifications-close").focus();}
  function closeNotifications(){document.getElementById("drawer-backdrop").hidden=true;const drawer=document.getElementById("notifications-drawer");drawer.classList.remove("open");drawer.setAttribute("aria-hidden","true");document.body.style.overflow="";document.getElementById("notifications-button").focus();}
  function closeDemoPanel(){const panel=document.getElementById("demo-panel");panel.hidden=true;document.getElementById("demo-mode-button").setAttribute("aria-expanded","false");}
  function validateTrimmed(form,names){for(const name of names){const control=form.elements.namedItem(name);if(control&&!String(control.value).trim()){control.setCustomValidity("Bitte geben Sie einen aussagekräftigen Wert ein.");control.reportValidity();control.addEventListener("input",()=>control.setCustomValidity(""),{once:true});return false;}}return true;}
  function createRequest(form,type){if(!form.reportValidity()||!validateTrimmed(form,["description"]))return;const data=new FormData(form),vehicle=state.vehicles.find((item)=>item.id===data.get("vehicle"));const request={id:`REQ-${state.nextIds.request++}`,type,typeLabel:type==="REPARATUR"?"Reparatur":"Gutachten",vehicleId:vehicle.id,vehicleName:vehicle.name,description:String(data.get("description")).trim(),date:String(data.get("date")),status:"OFFEN",statusLabel:"Offen",reportUploaded:false};request.type=type;state.requests.push(request);createRequestConversation(request);const requestLabel=type==="REPARATUR"?"Reparaturanfrage":"Gutachteranfrage";notify("NEUE_ANFRAGE",`Neue anonyme ${requestLabel} ${request.id}.`,type==="REPARATUR"?"WERKSTATT":"GUTACHTER");form.reset();render();showToast(`${requestLabel} ${request.id} wurde erstellt.`);}
  function createRequestConversation(request){const providerRole=request.type==="REPARATUR"?"WERKSTATT":"GUTACHTER",providerLabel=request.type==="REPARATUR"?"Werkstatt":"Gutachter",typeLabel=request.type==="REPARATUR"?"Reparaturanfrage":"Gutachteranfrage";state.conversations.push({id:`CONV-${state.nextIds.conversation++}`,type:`${request.type}ANFRAGE`,typeLabel,contextId:request.id,title:`${typeLabel}: ${request.vehicleName}`,roles:["KUNDE",providerRole],participants:[{role:"KUNDE",label:"Alex Beispiel",anonymousLabel:"Kunde #A-204"},{role:providerRole,label:providerLabel,anonymousLabel:`${providerLabel} (anonym)`}],messages:[]});}
  function openOfferDialog(requestId,providerRole){const request=state.requests.find((item)=>item.id===requestId);if(!request)return;openModal("Angebot abgeben",`<form class="form-grid" id="offer-form" data-request-id="${escapeHtml(requestId)}" data-provider-role="${escapeHtml(providerRole)}"><p class="muted">Anfrage ${escapeHtml(request.id)} · ${escapeHtml(request.vehicleName)}</p><div class="field"><label for="offer-price">Gesamtpreis in Euro</label><input id="offer-price" name="price" type="number" min="1" max="100000" step="0.01" required></div><div class="field"><label for="offer-date">Vorgeschlagener Termin</label><input id="offer-date" name="date" type="date" min="${today()}" required></div><div class="field"><label for="offer-duration">Voraussichtliche Dauer</label><input id="offer-duration" name="duration" required maxlength="120"></div><button class="button button-success" type="submit">Angebot anonym übermitteln</button></form>`);}
  function submitOffer(form){if(!form.reportValidity()||!validateTrimmed(form,["duration"]))return;const data=new FormData(form),price=Number(data.get("price"));if(!Number.isFinite(price)||price<=0)return;const role=form.dataset.providerRole,provider=role==="WERKSTATT"?"Werkstatt #309 · Bonn":"Gutachter #118 · Bonn";state.offers.push({id:`OFF-${state.nextIds.offer++}`,requestId:form.dataset.requestId,providerRole:role,provider,price:price.toLocaleString("de-DE",{minimumFractionDigits:2,maximumFractionDigits:2}),date:new Date(`${data.get("date")}T12:00:00`).toLocaleDateString("de-DE"),duration:String(data.get("duration")).trim(),cancellation:"Kostenfrei bis 24 Stunden vor Termin",accepted:false});notify("NEUES_ANGEBOT",`Für ${form.dataset.requestId} ist ein neues Angebot eingegangen.`,"KUNDE");closeModal();render();showToast("Das Angebot wurde anonym übermittelt.");}
  function requestAcceptOffer(offerId){const offer=state.offers.find((item)=>item.id===offerId);if(!offer)return;confirmAction({title:"Angebot annehmen",text:`Möchten Sie das Angebot von ${escapeHtml(offer.provider)} über ${escapeHtml(offer.price)} € verbindlich annehmen?`,confirmLabel:"Angebot annehmen",tone:"success"},()=>acceptOffer(offerId));}
  function acceptOffer(offerId){const offer=state.offers.find((item)=>item.id===offerId);if(!offer||offer.accepted)return;offer.accepted=true;const request=state.requests.find((item)=>item.id===offer.requestId);request.status="ANGENOMMEN";request.statusLabel="Angebot angenommen";ensureOrderConversation(request,offer);notify("ANGEBOT_ANGENOMMEN",`Ihr Angebot für ${offer.requestId} wurde angenommen.`,offer.providerRole);notify("TERMIN_BESTAETIGT",`Der Termin am ${offer.date} wurde vorgemerkt.`,"KUNDE");closeModal();render();showToast("Angebot angenommen. Die Beteiligten wurden benachrichtigt.");}
  function ensureOrderConversation(request,offer){if(state.conversations.some((item)=>item.type==="AUFTRAG"&&item.contextId===request.id))return;state.conversations.push({id:`CONV-${state.nextIds.conversation++}`,type:"AUFTRAG",typeLabel:"Auftrag",contextId:request.id,title:`Auftrag: ${request.vehicleName}`,roles:["KUNDE",offer.providerRole],participants:[{role:"KUNDE",label:"Alex Beispiel"},{role:offer.providerRole,label:offer.provider}],messages:[]});}
  function changeRequestDate(requestId){const request=state.requests.find((item)=>item.id===requestId),date=new Date(`${request.date}T12:00:00`);date.setDate(date.getDate()+1);request.date=date.toISOString().slice(0,10);notify("TERMIN_GEAENDERT",`Der Termin für ${requestId} wurde auf ${date.toLocaleDateString("de-DE")} geändert.`,"KUNDE");render();showToast("Termin wurde in der Demo um einen Tag verschoben.");}
  function requestComplete(requestId){confirmAction({title:"Auftrag abschließen",text:`Soll der Auftrag ${escapeHtml(requestId)} als abgeschlossen markiert werden?`,confirmLabel:"Auftrag abschließen",tone:"success"},()=>completeRequest(requestId));}
  function completeRequest(requestId){const request=state.requests.find((item)=>item.id===requestId);request.status="ABGESCHLOSSEN";request.statusLabel="Abgeschlossen";notify("AUFTRAG_ABGESCHLOSSEN",`Auftrag ${requestId} wurde abgeschlossen.`,"KUNDE");closeModal();render();showToast("Auftrag wurde abgeschlossen.");}
  function openProviderRegistration(key){const p=state.providers[key],label=key==="werkstatt"?"Werkstatt":"Gutachter";openModal(`${label} registrieren`,`<form class="form-grid" id="provider-form" data-provider-key="${key}"><div class="field"><label for="provider-name">Name des Betriebs</label><input id="provider-name" name="name" value="${escapeHtml(p.name)}" required maxlength="120"></div><div class="field"><label for="provider-email">Geschäftliche E-Mail-Adresse</label><input id="provider-email" name="email" type="email" value="kontakt@beispiel.de" required></div><label class="checkbox"><input name="terms" type="checkbox" required ${p.termsAccepted?"checked":""}><span>Ich akzeptiere die Plattformbedingungen und bestätige die Richtigkeit der Angaben.</span></label><p class="hint">Nach dem Absenden lautet der Status „In Prüfung“.</p><button class="button button-primary" type="submit">Registrierung einreichen</button></form>`);}
  function submitProvider(form){if(!form.reportValidity()||!validateTrimmed(form,["name"]))return;const data=new FormData(form),key=form.dataset.providerKey,p=state.providers[key];p.name=String(data.get("name")).trim();p.termsAccepted=true;p.status="IN_PRUEFUNG";p.statusReason="";notify("FREIGABESTATUS",`Die Registrierung von ${p.name} wurde zur Prüfung eingereicht.`,"ADMIN");closeModal();render();showToast("Registrierung eingereicht. Status: In Prüfung.");}
  function requestProviderStatus(value){const [key,status]=value.split(":"),p=state.providers[key],roleLabel=key==="werkstatt"?"Werkstatt":"Gutachter";if(status==="IN_PRUEFUNG"){changeProviderStatus(key,status,"");return;}const verbs={FREIGEGEBEN:"freigeben",ABGELEHNT:"ablehnen",GESPERRT:"sperren"},danger=["ABGELEHNT","GESPERRT"].includes(status);confirmAction({title:`${roleLabel} ${verbs[status]}`,text:`Möchten Sie „${escapeHtml(p.name)}“ wirklich ${verbs[status]}?`,confirmLabel:status==="FREIGEGEBEN"?"Freigeben":status==="ABGELEHNT"?"Ablehnen":"Sperren",tone:status==="FREIGEGEBEN"?"success":"danger",reason:danger},(reason)=>changeProviderStatus(key,status,reason));}
  function changeProviderStatus(key,status,reason){const p=state.providers[key];p.status=status;p.statusReason=reason;const role=key==="werkstatt"?"WERKSTATT":"GUTACHTER",labels={IN_PRUEFUNG:"in Prüfung gesetzt",FREIGEGEBEN:"freigegeben",ABGELEHNT:"abgelehnt",GESPERRT:"gesperrt"};notify("FREIGABESTATUS",`${p.name} wurde ${labels[status]}.`,role);closeModal();render();showToast(`Status aktualisiert: ${labels[status]}.`);}
  function openVehicle(){openModal("Fahrzeug hinzufügen",'<form class="form-grid" id="vehicle-form"><div class="field"><label for="vehicle-name">Hersteller und Modell</label><input id="vehicle-name" name="name" required maxlength="100"></div><div class="field"><label for="vehicle-plate">Kennzeichen</label><input id="vehicle-plate" name="plate" required maxlength="12"></div><div class="field"><label for="vehicle-vin">Fahrgestellnummer</label><input id="vehicle-vin" name="vin" required minlength="8" maxlength="17"></div><button class="button button-primary" type="submit">Fahrzeug speichern</button></form>');}
  function submitVehicle(form){if(!form.reportValidity()||!validateTrimmed(form,["name","plate","vin"]))return;const data=new FormData(form);state.vehicles.push({id:`VEH-${state.nextIds.vehicle++}`,name:String(data.get("name")).trim(),plate:String(data.get("plate")).trim().toUpperCase(),vin:String(data.get("vin")).trim().toUpperCase()});closeModal();render();showToast("Fahrzeug wurde hinzugefügt.");}
  function openSupport(){openModal("Supportfall eröffnen",'<form class="form-grid" id="support-form"><div class="field"><label for="support-title">Betreff</label><input id="support-title" name="title" required maxlength="120"></div><div class="field"><label for="support-description">Beschreibung</label><textarea id="support-description" name="description" required maxlength="1000"></textarea></div><button class="button button-primary" type="submit">Supportfall senden</button></form>');}
  function submitSupport(form){if(!form.reportValidity()||!validateTrimmed(form,["title","description"]))return;const data=new FormData(form),item={id:`SUP-${state.nextIds.support++}`,title:String(data.get("title")).trim(),status:"OFFEN",statusLabel:"Offen",participants:["Kunde #A-204","Kundensupport"],notes:[]};state.supportCases.push(item);state.conversations.push({id:`CONV-${state.nextIds.conversation++}`,type:"SUPPORTFALL",typeLabel:"Supportfall",contextId:item.id,title:item.title,roles:["KUNDE","KUNDENSUPPORT"],participants:[{role:"KUNDE",label:"Alex Beispiel"},{role:"KUNDENSUPPORT",label:"AutoAnonym Kundensupport"}],messages:[{id:`MSG-${state.nextIds.message++}`,senderRole:"KUNDE",sender:"Alex Beispiel",text:String(data.get("description")).trim(),createdAt:new Date().toISOString(),readBy:["KUNDE"]}]});notify("NEUER_SUPPORTFALL",`Neuer Supportfall ${item.id}: ${item.title}`,"KUNDENSUPPORT");closeModal();render();showToast(`Supportfall ${item.id} wurde eröffnet.`);}
  function openNote(caseId){openModal("Interne Notiz",`<form class="form-grid" id="note-form" data-case-id="${escapeHtml(caseId)}"><div class="field"><label for="note-text">Notiz für den Kundensupport</label><textarea id="note-text" name="note" required maxlength="800"></textarea></div><button class="button button-primary" type="submit">Notiz speichern</button></form>`);}
  function submitNote(form){if(!form.reportValidity()||!validateTrimmed(form,["note"]))return;state.supportCases.find((item)=>item.id===form.dataset.caseId).notes.push(String(new FormData(form).get("note")).trim());closeModal();render();showToast("Interne Notiz gespeichert.");}
  function requestEscalate(caseId){confirmAction({title:"Supportfall eskalieren",text:`Möchten Sie den Supportfall ${escapeHtml(caseId)} an den Admin eskalieren?`,confirmLabel:"Fall eskalieren",tone:"danger"},()=>escalateCase(caseId));}
  function escalateCase(caseId){const item=state.supportCases.find((support)=>support.id===caseId);item.status="ESKALIERT";item.statusLabel="Eskaliert";notify("SUPPORT_ESKALIERT",`Supportfall ${caseId} wurde eskaliert.`,"ADMIN");closeModal();render();showToast("Der Supportfall wurde eskaliert.");}
  function uploadReport(requestId){const item=state.requests.find((request)=>request.id===requestId);if(item&&!item.reportUploaded){item.reportUploaded=true;notify("GUTACHTEN_HOCHGELADEN",`Gutachten zu ${requestId} wurde als Demo hochgeladen.`,"KUNDE");render();showToast("Gutachten-Upload wurde simuliert.");}}
  document.addEventListener("click",(event)=>{const target=event.target.closest("button");if(!target)return;if(target.dataset.roleTarget)switchRole(target.dataset.roleTarget);else if(target.dataset.sectionTarget)switchSection(target.dataset.sectionTarget,target.dataset.requestFocus);else if(target.hasAttribute("data-portal-home"))switchSection(window.AutoAnonymNavigation.defaultSection(state.currentRole));else if(target.hasAttribute("data-portal-nav-toggle")){const nav=target.nextElementSibling,open=nav.classList.toggle("open");target.setAttribute("aria-expanded",String(open));}else if(target.dataset.conversationId){state.activeConversations[state.currentRole]=target.dataset.conversationId;render();}else if(target.dataset.acceptOffer)requestAcceptOffer(target.dataset.acceptOffer);else if(target.dataset.submitOffer)openOfferDialog(target.dataset.submitOffer,target.dataset.provider);else if(target.dataset.providerRegister)openProviderRegistration(target.dataset.providerRegister);else if(target.dataset.providerStatus)requestProviderStatus(target.dataset.providerStatus);else if(target.hasAttribute("data-open-vehicle"))openVehicle();else if(target.hasAttribute("data-open-support"))openSupport();else if(target.dataset.addNote)openNote(target.dataset.addNote);else if(target.dataset.escalateCase)requestEscalate(target.dataset.escalateCase);else if(target.dataset.changeDate)changeRequestDate(target.dataset.changeDate);else if(target.dataset.completeRequest)requestComplete(target.dataset.completeRequest);else if(target.dataset.uploadReport)uploadReport(target.dataset.uploadReport);else if(target.hasAttribute("data-close-modal"))closeModal();else if(target.hasAttribute("data-mark-notifications-read")){window.AutoAnonymBenachrichtigungen.markAllRead(state);render();showToast("Benachrichtigungen als gelesen markiert.");}});
  document.addEventListener("submit",(event)=>{event.preventDefault();const form=event.target;if(form.id==="repair-request-form")createRequest(form,"REPARATUR");else if(form.id==="expert-request-form")createRequest(form,"GUTACHTEN");else if(form.id==="offer-form")submitOffer(form);else if(form.id==="provider-form")submitProvider(form);else if(form.id==="vehicle-form")submitVehicle(form);else if(form.id==="support-form")submitSupport(form);else if(form.id==="note-form")submitNote(form);else if(form.id==="confirmation-form"&&pendingConfirmation){const callback=pendingConfirmation,reason=String(new FormData(form).get("reason")||"").trim();pendingConfirmation=null;callback(reason);}else if(form.matches("[data-thread-message-form]")){if(window.AutoAnonymNachrichten.submit(state,form,notify)){render();showToast("Nachricht wurde gesendet.");}}});
  document.getElementById("demo-mode-button").addEventListener("click",(event)=>{const panel=document.getElementById("demo-panel"),open=panel.hidden;panel.hidden=!open;event.currentTarget.setAttribute("aria-expanded",String(open));});
  document.getElementById("notifications-button").addEventListener("click",openNotifications);document.getElementById("notifications-close").addEventListener("click",closeNotifications);document.getElementById("drawer-backdrop").addEventListener("click",closeNotifications);document.getElementById("notifications-read").addEventListener("click",()=>{window.AutoAnonymBenachrichtigungen.markAllRead(state);window.AutoAnonymBenachrichtigungen.render(state,escapeHtml);render();});document.getElementById("modal-close").addEventListener("click",closeModal);document.getElementById("modal-backdrop").addEventListener("click",(event)=>{if(event.target.id==="modal-backdrop")closeModal();});document.addEventListener("keydown",(event)=>{if(event.key==="Escape"){if(!document.getElementById("modal-backdrop").hidden)closeModal();else if(document.getElementById("notifications-drawer").classList.contains("open"))closeNotifications();else closeDemoPanel();}else if(event.key==="Tab"&&!document.getElementById("modal-backdrop").hidden){trapModalFocus(event);}});
  function trapModalFocus(event){const modal=document.querySelector(".modal"),focusable=[...modal.querySelectorAll('button:not([disabled]), input:not([disabled]), textarea:not([disabled]), select:not([disabled]), [href]')];if(!focusable.length)return;const first=focusable[0],last=focusable[focusable.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}
  function today(){return new Date().toISOString().slice(0,10);}render();
}());
