(function(){
  "use strict";
  function render(state,h){const p=state.providers.gutachter,enabled=p.status==="FREIGEGEBEN",section=state.activeSections.GUTACHTER;const locked=enabled?[]:["anfragen","angebote","auftraege","gutachten"];document.getElementById("view-gutachter").innerHTML=header(p)+window.AutoAnonymNavigation.render("GUTACHTER",section,locked)+`<div class="portal-content">${locked.includes(section)?lockedView(p.status):content(section,state,h,enabled)}</div>`;}
  function header(p){return `<header class="portal-context"><p class="eyebrow">Gutachterportal</p><div class="split"><div><h1>${p.name}</h1><p class="muted">Anfragen, Aufträge und Gutachten übersichtlich bearbeiten.</p></div>${window.AutoAnonymStatus.badge(p.status)}</div></header>`;}
  function content(section,state,h,enabled){if(section==="dashboard")return dashboard(state,enabled);if(section==="anfragen")return requests(state,h);if(section==="angebote")return offers(state,h);if(section==="auftraege")return orders(state,h,false);if(section==="gutachten")return orders(state,h,true);if(section==="nachrichten")return window.AutoAnonymNachrichten.render(state,h,"GUTACHTER");if(section==="benachrichtigungen")return window.AutoAnonymBenachrichtigungen.inline(state,h,"GUTACHTER");return profile(state,h);}
  function dashboard(state,enabled){const own=state.offers.filter(isOwn);return `<section class="card status-panel ${enabled?"success":""}"><p class="eyebrow">Freigabestatus</p><h2>${enabled?"Gutachterprofil aktiv":"Admin-Freigabe erforderlich"}</h2><p class="muted">${statusMessage(state.providers.gutachter.status)}</p></section><section class="section grid grid-3"><article class="card metric-card"><p class="eyebrow">Neue Anfragen</p><div class="metric">${enabled?state.requests.filter((item)=>item.type==="GUTACHTEN"&&item.status==="OFFEN").length:"–"}</div></article><article class="card metric-card"><p class="eyebrow">Meine Angebote</p><div class="metric">${own.length}</div></article><article class="card metric-card"><p class="eyebrow">Gutachten offen</p><div class="metric">${own.filter((item)=>item.accepted&&!state.requests.find((request)=>request.id===item.requestId)?.reportUploaded).length}</div></article></section>`;}
  function requests(state,h){const items=state.requests.filter((item)=>item.type==="GUTACHTEN"&&item.status==="OFFEN");return `<section><div class="section-heading"><div><p class="eyebrow">Neue Vorgänge</p><h2>Gutachteranfragen</h2></div></div><div class="stack">${items.length?items.map((item)=>{const offered=state.offers.some((offer)=>offer.requestId===item.id&&isOwn(offer));return `<article class="list-card"><div class="split"><div>${window.AutoAnonymStatus.badge(item.status)}<h3>${h(item.vehicleName)}</h3></div><strong>${formatDate(item.date)}</strong></div><p>${h(item.description)}</p>${offered?'<span class="badge badge-info">Angebot abgegeben</span>':`<button class="button button-success" type="button" data-submit-offer="${item.id}" data-provider="GUTACHTER">Angebot abgeben</button>`}</article>`;}).join(""):'<div class="empty">Aktuell keine Gutachteranfragen.</div>'}</div></section>`;}
  function offers(state,h){const items=state.offers.filter(isOwn);return `<section><p class="eyebrow">Kalkulationen</p><h2>Meine Angebote</h2><div class="stack">${items.length?items.map((item)=>`<article class="list-card"><div class="split"><div>${window.AutoAnonymStatus.badge(item.accepted?"ANGENOMMEN":"OFFEN")}<h3>${h(item.requestId)}</h3></div><strong>${h(item.price)} €</strong></div><p class="small muted">${h(item.duration)} · ${h(item.date)}</p></article>`).join(""):'<div class="empty">Noch keine Angebote abgegeben.</div>'}</div></section>`;}
  function orders(state,h,reportsOnly){const accepted=state.offers.filter((item)=>isOwn(item)&&item.accepted);return `<section><p class="eyebrow">${reportsOnly?"Dokumente":"Beauftragte Fälle"}</p><h2>${reportsOnly?"Gutachten":"Aufträge"}</h2><div class="stack">${accepted.length?accepted.map((offer)=>{const item=state.requests.find((request)=>request.id===offer.requestId);return `<article class="list-card"><div class="split"><div>${window.AutoAnonymStatus.badge(item.reportUploaded?"ABGESCHLOSSEN":"IN_BEARBEITUNG")}<h3>${h(item.vehicleName)}</h3></div><strong>${formatDate(item.date)}</strong></div><p>${h(item.description)}</p>${item.reportUploaded?'<span class="badge badge-success">Gutachten hochgeladen</span>':`<button class="button button-primary" type="button" data-upload-report="${item.id}">Gutachten-Upload simulieren</button>`}</article>`;}).join(""):'<div class="empty">Keine beauftragten Gutachten.</div>'}</div></section>`;}
  function profile(state,h){const p=state.providers.gutachter;return `<section class="grid grid-2"><article class="card"><p class="eyebrow">Gutachterprofil</p><h2>${h(p.name)}</h2><p class="muted">Kfz-Sachverständigenbüro · Bedingungen akzeptiert</p><button class="button button-primary" type="button" data-provider-register="gutachter">Registrierung bearbeiten</button></article><article class="card"><p class="eyebrow">Status</p><h2>${window.AutoAnonymStatus.label(p.status)}</h2><p class="muted">${statusMessage(p.status)}</p></article></section>`;}
  function lockedView(status){return `<section class="card locked-panel"><p class="eyebrow">Bereich gesperrt</p><h2>Freigabe erforderlich</h2><p>${statusMessage(status)}</p><button class="button button-secondary" type="button" data-section-target="profil">Zum Profil</button></section>`;}
  function statusMessage(status){return {IN_PRUEFUNG:"Ihre Nachweise werden geprüft. Danach werden Anfragen und Aufträge freigeschaltet.",FREIGEGEBEN:"Ihr Profil ist freigegeben und kann alle Gutachterfunktionen nutzen.",ABGELEHNT:"Die Registrierung wurde abgelehnt. Prüfen Sie Ihre Angaben.",GESPERRT:"Das Profil ist gesperrt. Wenden Sie sich an den Kundensupport."}[status];}
  function isOwn(offer){return offer.providerRole==="GUTACHTER"&&offer.provider.includes("#118");}function formatDate(value){return new Date(`${value}T12:00:00`).toLocaleDateString("de-DE");}
  window.AutoAnonymGutachter={render};
}());
