(function () {
  "use strict";
  function render(state, h) {
    const section = state.activeSections.KUNDE;
    document.getElementById("view-kunde").innerHTML = portalHeader() + window.AutoAnonymNavigation.render("KUNDE", section, []) + `<div class="portal-content">${content(section, state, h)}</div>`;
  }
  function portalHeader() { return '<header class="portal-context"><p class="eyebrow">Kundenportal</p><h1>Guten Tag, Alex</h1><p class="muted">Ihre Fahrzeuge, Anfragen und Aufträge sicher an einem Ort.</p></header>'; }
  function content(section, state, h) {
    if (section === "start") return start(state, h);
    if (section === "fahrzeuge") return vehicles(state, h);
    if (section === "anfragen") return requests(state, h);
    if (section === "auftraege") return orders(state, h);
    if (section === "nachrichten") return window.AutoAnonymNachrichten.render(state, h, "KUNDE");
    if (section === "support") return support(state, h);
    return profile();
  }
  function start(state, h) {
    const open = state.requests.filter((item) => item.status === "OFFEN").length;
    const newOffers = state.offers.filter((item) => !item.accepted && state.requests.find((request) => request.id === item.requestId)?.status === "OFFEN").length;
    const appointments = state.offers.filter((item) => item.accepted).length;
    const unread = window.AutoAnonymNachrichten.totalUnread(state, "KUNDE");
    return `<section><div class="section-heading"><div><p class="eyebrow">Schnell starten</p><h2>Was möchten Sie erledigen?</h2></div><span class="badge badge-success">Anonymität aktiv</span></div><div class="grid grid-2"><button class="card quick-action" type="button" data-section-target="anfragen" data-request-focus="repair"><span class="quick-icon">R</span><span><strong>Reparatur anfragen</strong><small class="muted">Schaden beschreiben und Werkstattangebote erhalten</small></span></button><button class="card quick-action" type="button" data-section-target="anfragen" data-request-focus="expert"><span class="quick-icon">G</span><span><strong>Kfz-Gutachter beauftragen</strong><small class="muted">Gutachteranfrage anonym einstellen</small></span></button></div></section>
      <section class="section"><div class="section-heading"><div><p class="eyebrow">Übersicht</p><h2>Das Wichtigste auf einen Blick</h2></div></div><div class="grid grid-2"><article class="card metric-card"><p class="eyebrow">Offene Anfragen</p><div class="metric">${open}</div><button class="button button-secondary button-small" data-section-target="anfragen" type="button">Anzeigen</button></article><article class="card metric-card"><p class="eyebrow">Neue Angebote</p><div class="metric">${newOffers}</div><button class="button button-secondary button-small" data-section-target="anfragen" type="button">Vergleichen</button></article><article class="card metric-card"><p class="eyebrow">Kommende Termine</p><div class="metric">${appointments}</div><button class="button button-secondary button-small" data-section-target="auftraege" type="button">Zu den Aufträgen</button></article><article class="card metric-card"><p class="eyebrow">Ungelesene Nachrichten</p><div class="metric">${unread}</div><button class="button button-secondary button-small" data-section-target="nachrichten" type="button">Nachrichten öffnen</button></article></div></section>`;
  }
  function requestForms(state, h) { return `<div class="grid grid-2"><form class="card form-grid" id="repair-request-form"><div><p class="eyebrow">Werkstattanfrage</p><h2>Reparatur anfragen</h2></div>${vehicleSelect(state,h,"repair")}<div class="field"><label for="repair-description">Schadensbeschreibung</label><textarea id="repair-description" name="description" required maxlength="1000"></textarea></div><div class="field"><label for="repair-date">Wunschtermin</label><input id="repair-date" name="date" type="date" required min="${today()}"></div><button class="button button-primary" type="submit">Anfrage senden</button></form><form class="card form-grid" id="expert-request-form"><div><p class="eyebrow">Gutachteranfrage</p><h2>Kfz-Gutachter beauftragen</h2></div>${vehicleSelect(state,h,"expert")}<div class="field"><label for="expert-description">Anlass des Gutachtens</label><textarea id="expert-description" name="description" required maxlength="1000"></textarea></div><div class="field"><label for="expert-date">Wunschtermin</label><input id="expert-date" name="date" type="date" required min="${today()}"></div><button class="button button-secondary" type="submit">Gutachteranfrage senden</button></form></div>`; }
  function requests(state, h) { return `<section><div class="section-heading"><div><p class="eyebrow">Neue Anfrage</p><h2>Leistung anfragen</h2></div></div>${requestForms(state,h)}</section><section class="section"><div class="section-heading"><div><p class="eyebrow">Status</p><h2>Meine Anfragen und Angebote</h2></div></div><div class="stack">${state.requests.map((item) => `<article class="list-card"><div class="split"><div>${window.AutoAnonymStatus.badge(item.status)}<h3>${h(item.typeLabel)} · ${h(item.vehicleName)}</h3><span class="hint">${h(item.id)}</span></div><strong>${formatDate(item.date)}</strong></div><p>${h(item.description)}</p>${offersFor(item,state,h)}</article>`).join("")}</div></section>`; }
  function offersFor(request,state,h) { const offers=state.offers.filter((item)=>item.requestId===request.id); return offers.length ? `<div class="stack">${offers.map((offer)=>`<div class="list-card"><div class="split"><div><strong>${h(offer.provider)}</strong><p class="small muted">${h(offer.duration)} · ${h(offer.cancellation)}</p></div><strong>${h(offer.price)} €</strong></div>${offer.accepted?'<span class="badge badge-success">Angenommen</span>':request.status!=="OFFEN"?'<span class="badge badge-info">Vergabe abgeschlossen</span>':`<button class="button button-primary button-small" type="button" data-accept-offer="${offer.id}">Angebot annehmen</button>`}</div>`).join("")}</div>`:'<p class="hint">Noch keine Angebote eingegangen.</p>'; }
  function vehicles(state,h) { return `<section><div class="section-heading"><div><p class="eyebrow">Meine Garage</p><h2>Fahrzeuge</h2></div><button class="button button-primary" type="button" data-open-vehicle>Fahrzeug hinzufügen</button></div><div class="grid grid-2">${state.vehicles.map((item)=>`<article class="card"><div class="split"><div><h3>${h(item.name)}</h3><p class="small muted">${h(item.plate)} · VIN ${h(item.vin)}</p></div><span class="badge badge-success">Verifiziert</span></div></article>`).join("")}</div></section>`; }
  function orders(state,h) { const orders=state.requests.filter((item)=>["ANGENOMMEN","ABGESCHLOSSEN"].includes(item.status)); return `<section><div class="section-heading"><div><p class="eyebrow">Beauftragte Leistungen</p><h2>Aufträge</h2></div></div><div class="stack">${orders.length?orders.map((item)=>`<article class="list-card"><div class="split"><div>${window.AutoAnonymStatus.badge(item.status)}<h3>${h(item.typeLabel)} · ${h(item.vehicleName)}</h3></div><strong>${formatDate(item.date)}</strong></div><p>${h(item.description)}</p></article>`).join(""):'<div class="empty">Noch keine Aufträge vorhanden.</div>'}</div></section>`; }
  function support(state,h) { return `<section><div class="section-heading"><div><p class="eyebrow">Hilfe & Support</p><h2>Meine Supportfälle</h2></div><button class="button button-primary" type="button" data-open-support>Supportfall eröffnen</button></div><div class="stack">${state.supportCases.map((item)=>`<article class="list-card"><div class="split"><div>${window.AutoAnonymStatus.badge(item.status)}<h3>${h(item.title)}</h3></div><span class="hint">${h(item.id)}</span></div></article>`).join("")}</div></section>`; }
  function profile() { return '<section class="grid grid-2"><article class="card"><p class="eyebrow">Persönliche Daten</p><h2>Alex Beispiel</h2><p class="muted">alex@beispiel.de<br>Konto verifiziert</p><span class="badge badge-info">Profilbearbeitung vorbereitet</span></article><article class="card"><p class="eyebrow">Datenschutz</p><h2>Anonyme Vermittlung</h2><p class="muted">Kontaktdaten werden erst nach einer verbindlichen Vergabe für die Beteiligten sichtbar.</p></article></section>'; }
  function vehicleSelect(state,h,prefix){return `<div class="field"><label for="${prefix}-vehicle">Fahrzeug</label><select id="${prefix}-vehicle" name="vehicle">${state.vehicles.map((item)=>`<option value="${item.id}">${h(item.name)} · ${h(item.plate)}</option>`).join("")}</select></div>`;}
  function today(){return new Date().toISOString().slice(0,10);} function formatDate(value){return new Date(`${value}T12:00:00`).toLocaleDateString("de-DE");}
  window.AutoAnonymKunde={render};
}());
