(function(){
  "use strict";
  function render(state,h){const section=state.activeSections.KUNDENSUPPORT;document.getElementById("view-kundensupport").innerHTML='<header class="portal-context"><p class="eyebrow">Supportportal</p><h1>Kundensupport</h1><p class="muted">Fälle bearbeiten, intern dokumentieren und gezielt eskalieren.</p></header>'+window.AutoAnonymNavigation.render("KUNDENSUPPORT",section,[])+`<div class="portal-content">${content(section,state,h)}</div>`;}
  function content(section,state,h){if(section==="dashboard")return dashboard(state);if(section==="neu")return cases(state,h,"OFFEN","Neue Supportfälle");if(section==="bearbeitung")return cases(state,h,"IN_BEARBEITUNG","In Bearbeitung");if(section==="eskaliert")return cases(state,h,"ESKALIERT","Eskalierte Fälle");if(section==="nachrichten")return window.AutoAnonymNachrichten.render(state,h,"KUNDENSUPPORT");return window.AutoAnonymBenachrichtigungen.inline(state,h,"KUNDENSUPPORT");}
  function dashboard(state){return `<section class="grid grid-3"><article class="card metric-card"><p class="eyebrow">Neu</p><div class="metric">${count(state,"OFFEN")}</div><button class="button button-secondary button-small" data-section-target="neu" type="button">Öffnen</button></article><article class="card metric-card"><p class="eyebrow">In Bearbeitung</p><div class="metric">${count(state,"IN_BEARBEITUNG")}</div><button class="button button-secondary button-small" data-section-target="bearbeitung" type="button">Öffnen</button></article><article class="card metric-card"><p class="eyebrow">Eskaliert</p><div class="metric">${count(state,"ESKALIERT")}</div><button class="button button-secondary button-small" data-section-target="eskaliert" type="button">Öffnen</button></article></section><section class="section card"><p class="eyebrow">Berechtigungen</p><h2>Support mit klar begrenzten Rechten</h2><p class="muted">Sie können kommunizieren, interne Notizen pflegen und Fälle eskalieren. Partnerfreigaben und Systemeinstellungen bleiben dem Admin vorbehalten.</p></section>`;}
  function cases(state,h,status,title){const items=state.supportCases.filter((item)=>item.status===status);return `<section><div class="section-heading"><div><p class="eyebrow">Fallübersicht</p><h2>${title}</h2></div></div><div class="stack">${items.length?items.map((item)=>caseCard(item,h)).join(""):'<div class="empty">Keine Fälle in diesem Bereich.</div>'}</div></section>`;}
  function caseCard(item,h){return `<article class="list-card"><div class="split"><div>${window.AutoAnonymStatus.badge(item.status)}<h3>${h(item.title)}</h3></div><span class="hint">${h(item.id)}</span></div><p class="small muted">Beteiligte: ${h(item.participants.join(", "))}</p>${item.notes.map((note)=>`<p class="note small"><strong>Interne Notiz:</strong> ${h(note)}</p>`).join("")}<div class="action-row"><button class="button button-secondary button-small" type="button" data-add-note="${item.id}">Interne Notiz</button><button class="button button-danger button-small" type="button" data-escalate-case="${item.id}" ${item.status==="ESKALIERT"?"disabled":""}>Fall eskalieren</button></div></article>`;}
  function count(state,status){return state.supportCases.filter((item)=>item.status===status).length;}
  window.AutoAnonymSupport={render};
}());
