(function () {
  "use strict";
  function render(state,h){
    const profile=state.providers.werkstatt, enabled=profile.status==="FREIGEGEBEN", section=state.activeSections.WERKSTATT;
    const locked=enabled?[]:["anfragen","angebote","auftraege"];
    const body=locked.includes(section)?lockedView(profile.status):content(section,state,h,enabled);
    document.getElementById("view-werkstatt").innerHTML=portalHeader(profile)+window.AutoAnonymNavigation.render("WERKSTATT",section,locked)+`<div class="portal-content">${body}</div>`;
  }
  function portalHeader(profile){return `<header class="portal-context"><p class="eyebrow">Werkstattportal</p><div class="split"><div><h1>${profile.name}</h1><p class="muted">Anfragen, Angebote und Aufträge für Ihren Betrieb.</p></div>${window.AutoAnonymStatus.badge(profile.status)}</div></header>`;}
  function content(section,state,h,enabled){if(section==="dashboard")return dashboard(state,h,enabled);if(section==="anfragen")return requestList(state,h);if(section==="angebote")return offers(state,h);if(section==="auftraege")return orders(state,h);if(section==="nachrichten")return window.AutoAnonymNachrichten.render(state,h,"WERKSTATT");if(section==="benachrichtigungen")return window.AutoAnonymBenachrichtigungen.inline(state,h,"WERKSTATT");return profile(state,h);}
  function dashboard(state,h,enabled){const ownOffers=state.offers.filter(isOwn);const ownOrders=ownOffers.filter((item)=>item.accepted);return `<section class="card status-panel ${enabled?"success":""}"><div class="split"><div><p class="eyebrow">Freigabestatus</p><h2>${enabled?"Ihr Betrieb ist aktiv":"Prüfung noch nicht abgeschlossen"}</h2><p class="muted">${statusMessage(state.providers.werkstatt.status)}</p></div><button class="button button-secondary" type="button" data-section-target="profil">Profil anzeigen</button></div></section><section class="section"><div class="grid grid-3"><article class="card metric-card"><p class="eyebrow">Neue Anfragen</p><div class="metric">${enabled?state.requests.filter((item)=>item.type==="REPARATUR"&&item.status==="OFFEN").length:"–"}</div></article><article class="card metric-card"><p class="eyebrow">Meine Angebote</p><div class="metric">${ownOffers.length}</div></article><article class="card metric-card"><p class="eyebrow">Aktive Aufträge</p><div class="metric">${ownOrders.length}</div></article></div></section>`;}
  function requestList(state,h){const items=state.requests.filter((item)=>item.type==="REPARATUR"&&item.status==="OFFEN");return `<section><div class="section-heading"><div><p class="eyebrow">Im Arbeitsradius</p><h2>Neue Reparaturanfragen</h2></div><span class="badge badge-info">25 km um Bonn</span></div><div class="stack">${items.length?items.map((item)=>requestCard(item,state,h)).join(""):'<div class="empty">Aktuell keine neuen Anfragen.</div>'}</div></section>`;}
  function requestCard(item,state,h){const offered=state.offers.some((offer)=>offer.requestId===item.id&&isOwn(offer));return `<article class="list-card"><div class="split"><div>${window.AutoAnonymStatus.badge(item.status)}<h3>${h(item.vehicleName)}</h3></div><strong>${formatDate(item.date)}</strong></div><p>${h(item.description)}</p>${offered?'<span class="badge badge-info">Angebot abgegeben</span>':`<button class="button button-success" type="button" data-submit-offer="${item.id}" data-provider="WERKSTATT">Angebot abgeben</button>`}</article>`;}
  function offers(state,h){const items=state.offers.filter(isOwn);return `<section><div class="section-heading"><div><p class="eyebrow">Kalkulationen</p><h2>Meine Angebote</h2></div></div><div class="stack">${items.length?items.map((item)=>`<article class="list-card"><div class="split"><div>${window.AutoAnonymStatus.badge(item.accepted?"ANGENOMMEN":"OFFEN")}<h3>${h(item.requestId)}</h3></div><strong>${h(item.price)} €</strong></div><p class="small muted">${h(item.duration)} · Termin ${h(item.date)}</p></article>`).join(""):'<div class="empty">Noch keine Angebote abgegeben.</div>'}</div></section>`;}
  function orders(state,h){const accepted=state.offers.filter((item)=>isOwn(item)&&item.accepted);return `<section><div class="section-heading"><div><p class="eyebrow">Beauftragte Arbeiten</p><h2>Aufträge</h2></div></div><div class="stack">${accepted.length?accepted.map((offer)=>{const item=state.requests.find((request)=>request.id===offer.requestId);return `<article class="list-card"><div class="split"><div>${window.AutoAnonymStatus.badge(item.status)}<h3>${h(item.vehicleName)}</h3></div><strong>${formatDate(item.date)}</strong></div><p>${h(item.description)}</p>${item.status==="ABGESCHLOSSEN"?'<span class="badge badge-success">Auftrag abgeschlossen</span>':`<div class="action-row"><button class="button button-secondary" type="button" data-change-date="${item.id}">Termin ändern</button><button class="button button-success" type="button" data-complete-request="${item.id}">Auftrag abschließen</button></div>`}</article>`;}).join(""):'<div class="empty">Keine aktiven Aufträge.</div>'}</div></section>`;}
  function profile(state,h){const p=state.providers.werkstatt;return `<section class="grid grid-2"><article class="card"><p class="eyebrow">Betriebsprofil</p><h2>${h(p.name)}</h2><p class="muted">Kfz-Meisterbetrieb · 25 km Arbeitsradius<br>Bedingungen akzeptiert</p><button class="button button-primary" type="button" data-provider-register="werkstatt">Registrierung bearbeiten</button></article><article class="card"><p class="eyebrow">Status</p><h2>${window.AutoAnonymStatus.label(p.status)}</h2><p class="muted">${statusMessage(p.status)}</p></article></section>`;}
  function lockedView(status){return `<section class="card locked-panel"><p class="eyebrow">Bereich gesperrt</p><h2>Diese Funktion ist noch nicht verfügbar</h2><p>${statusMessage(status)}</p><button class="button button-secondary" type="button" data-section-target="profil">Zum Profil und Freigabestatus</button></section>`;}
  function statusMessage(status){return {IN_PRUEFUNG:"Ihre Unterlagen werden vom Admin geprüft. Danach werden Anfragen und Aufträge freigeschaltet.",FREIGEGEBEN:"Ihr Betrieb ist freigegeben und kann alle Werkstattfunktionen nutzen.",ABGELEHNT:"Die Registrierung wurde abgelehnt. Prüfen Sie die Angaben im Profil.",GESPERRT:"Der Betrieb ist gesperrt. Wenden Sie sich an den Kundensupport."}[status];}
  function isOwn(offer){return offer.providerRole==="WERKSTATT"&&offer.provider.includes("#309");}function formatDate(value){return new Date(`${value}T12:00:00`).toLocaleDateString("de-DE");}
  window.AutoAnonymWerkstatt={render};
}());
